export const endpoints = {
  auth: {
    login: "/auth/login",
    refresh: "/auth/refresh",
    me: "/auth/me",
    logout: "/auth/logout",
  },
  inquiries: {
    contact: "/inquiries/contact",
    list: "/inquiries",
    updateStatus: (id: string) => `/inquiries/${id}/status`,
  },
  users: {
    list: "/users",
    detail: (id: string) => `/users/${id}`,
  },
  organizations: {
    list: "/organizations",
    detail: (id: string) => `/organizations/${id}`,
    currentSettings: "/organization-settings/current",
  },
  roles: {
    list: "/roles",
    detail: (id: string) => `/roles/${id}`,
  },
  permissions: {
    list: "/permissions",
  },
  students: {
    list: "/students",
    import: "/students/import",
    importSample: "/students/import/sample",
    detail: (id: string) => `/students/${id}`,
  },
  batches: {
    list: "/batches",
    detail: (id: string) => `/batches/${id}`,
  },
  fees: {
    plans: "/fees/plans",
    records: "/fees/records",
    recordDetail: (id: string) => `/fees/records/${id}`,
  },
  attendance: {
    list: "/attendance",
    detail: (id: string) => `/attendance/${id}`,
  },
  reminders: {
    list: "/reminders",
    detail: (id: string) => `/reminders/${id}`,
    templates: "/reminders/templates",
    resetDefaultTemplates: "/reminders/templates/reset-defaults",
    templateDetail: (id: string) => `/reminders/templates/${id}`,
    rules: "/reminders/rules",
    ruleDetail: (id: string) => `/reminders/rules/${id}`,
    providerSettings: "/reminders/provider-settings",
    processDue: "/reminders/automation/process-due",
  },
  activityLogs: {
    list: "/activity-logs",
  },
  reports: {
    summary: "/reports/summary",
    totalStudents: "/reports/students/total",
    activeStudents: "/reports/students/active",
    enrollmentTrend: "/reports/students/enrollment-trend",
    studentStatusBreakdown: "/reports/students/status-breakdown",
    studentBatchDistribution: "/reports/students/batch-distribution",
    userRoleDistribution: "/reports/users/role-distribution",
    userStatusSummary: "/reports/users/status-summary",
    batchStatusSummary: "/reports/batches/status-summary",
    monthlyFeeCollection: "/reports/fees/monthly-collection",
    feeCollectionTrend: "/reports/fees/collection-trend",
    batchCollection: "/reports/fees/batch-collection",
    feeStatusBreakdown: "/reports/fees/status-breakdown",
    unpaidFees: "/reports/fees/unpaid",
    attendanceSummary: "/reports/attendance/summary",
    attendanceStatusBreakdown: "/reports/attendance/status-breakdown",
    attendanceDailyTrend: "/reports/attendance/daily-trend",
    attendanceBatchSummary: "/reports/attendance/batch-summary",
    reminderChannelBreakdown: "/reports/reminders/channel-breakdown",
    reminderStatusBreakdown: "/reports/reminders/status-breakdown",
    reminderDailyTrend: "/reports/reminders/daily-trend",
  },
} as const;
