export const endpoints = {
  auth: {
    login: "/auth/login",
    refresh: "/auth/refresh",
    me: "/auth/me",
    logout: "/auth/logout",
    security: "/auth/security",
    revokeSession: (sessionId: string) => `/auth/sessions/${sessionId}/revoke`,
  },
  portalAuth: {
    login: "/portal-auth/login",
    refresh: "/portal-auth/refresh",
    me: "/portal-auth/me",
    logout: "/portal-auth/logout",
  },
  portal: {
    dashboard: "/portal/dashboard",
    reportCard: "/portal/report-card",
    activityFeed: "/portal/activity-feed",
    acknowledgements: "/portal/acknowledgements",
    acknowledgeItem: "/portal/acknowledgements/acknowledge",
    announcements: "/portal/announcements",
    fees: "/portal/fees",
    uploadPaymentProof: (feeRecordId: string) => `/portal/fees/${feeRecordId}/payment-proofs`,
    paymentProofDownload: (proofId: string) => `/portal/fee-proofs/${proofId}/download`,
    documents: "/portal/documents",
    documentDownload: (documentId: string) => `/portal/documents/${encodeURIComponent(documentId)}/download`,
    assignments: "/portal/assignments",
    assignmentDetail: (assignmentId: string) => `/portal/assignments/${assignmentId}`,
    assignmentSubmission: (assignmentId: string) => `/portal/assignments/${assignmentId}/submission`,
    assignmentSubmit: (assignmentId: string) => `/portal/assignments/${assignmentId}/submit`,
    assessments: "/portal/assessments",
    assessmentDetail: (assessmentId: string) => `/portal/assessments/${assessmentId}`,
    assessmentStart: (assessmentId: string) => `/portal/assessments/${assessmentId}/start`,
    assessmentAttemptAnswers: (attemptId: string) => `/portal/assessments/attempts/${attemptId}/answers`,
    assessmentAttemptSubmit: (attemptId: string) => `/portal/assessments/attempts/${attemptId}/submit`,
  },
  inquiries: {
    contact: "/inquiries/contact",
    list: "/inquiries",
    updateStatus: (id: string) => `/inquiries/${id}/status`,
  },
  users: {
    list: "/users",
    detail: (id: string) => `/users/${id}`,
    bulkDelete: "/users/bulk-delete",
    bulkStatus: "/users/bulk-status",
  },
  organizations: {
    list: "/organizations",
    detail: (id: string) => `/organizations/${id}`,
    billingEntries: (id: string) => `/organizations/${id}/billing-entries`,
    billingEntryDetail: (id: string, entryId: string) => `/organizations/${id}/billing-entries/${entryId}`,
    currentSettings: "/organization-settings/current",
  },
  organizationAssets: {
    list: "/organization-assets/current",
    detail: (id: string) => `/organization-assets/current/${id}`,
    download: (id: string) => `/organization-assets/current/${id}/download`,
  },
  roles: {
    list: "/roles",
    detail: (id: string) => `/roles/${id}`,
  },
  permissions: {
    list: "/permissions",
  },
  students: {
    list: "/students",
    import: "/students/import",
    importSample: "/students/import/sample",
    detail: (id: string) => `/students/${id}`,
    portalLogin: (id: string) => `/students/${id}/portal-login`,
    parentPortalLogin: (id: string) => `/students/${id}/parent-portal-login`,
    portalAccess: (id: string) => `/students/${id}/portal-access`,
    documents: (id: string) => `/students/${id}/documents`,
    documentDetail: (studentId: string, documentId: string) => `/students/${studentId}/documents/${documentId}`,
    documentDownload: (studentId: string, documentId: string) => `/students/${studentId}/documents/${documentId}/download`,
    bulkDelete: "/students/bulk-delete",
    bulkStatus: "/students/bulk-status",
  },
  batches: {
    list: "/batches",
    detail: (id: string) => `/batches/${id}`,
    bulkDelete: "/batches/bulk-delete",
    bulkStatus: "/batches/bulk-status",
  },
  academicSessions: {
    list: "/academic-sessions",
    detail: (id: string) => `/academic-sessions/${id}`,
    bulkDelete: "/academic-sessions/bulk-delete",
    bulkStatus: "/academic-sessions/bulk-status",
  },
  subjects: {
    list: "/subjects",
    detail: (id: string) => `/subjects/${id}`,
    bulkDelete: "/subjects/bulk-delete",
    bulkStatus: "/subjects/bulk-status",
  },
  teachers: {
    list: "/teachers",
    detail: (id: string) => `/teachers/${id}`,
    bulkDelete: "/teachers/bulk-delete",
    bulkStatus: "/teachers/bulk-status",
  },
  batchSubjectAssignments: {
    list: "/batch-subject-assignments",
    detail: (id: string) => `/batch-subject-assignments/${id}`,
    bulkDelete: "/batch-subject-assignments/bulk-delete",
    bulkStatus: "/batch-subject-assignments/bulk-status",
  },
  timetables: {
    list: "/timetables",
    detail: (id: string) => `/timetables/${id}`,
    bulkDelete: "/timetables/bulk-delete",
  },
  onlineClasses: {
    list: "/online-classes/sessions",
    detail: (id: string) => `/online-classes/sessions/${id}`,
    providerSettings: "/online-classes/provider-settings",
    runAutomation: "/online-classes/automation/run",
    automationSummary: "/online-classes/automation/summary",
    alerts: "/online-classes/alerts",
    generateMeet: (id: string) => `/online-classes/sessions/${id}/google-meet`,
    syncGoogleMeet: (id: string) => `/online-classes/sessions/${id}/google-meet/sync`,
    participants: (id: string) => `/online-classes/sessions/${id}/participants`,
    processAttendance: (id: string) => `/online-classes/sessions/${id}/process-attendance`,
  },
  exams: {
    list: "/exams",
    detail: (id: string) => `/exams/${id}`,
    bulkDelete: "/exams/bulk-delete",
    bulkPublish: "/exams/bulk-publish",
  },
  assignments: {
    list: "/assignments",
    detail: (id: string) => `/assignments/${id}`,
    bulkDelete: "/assignments/bulk-delete",
    reviewSubmission: (submissionId: string) => `/assignments/submissions/${submissionId}/review`,
  },
  assessments: {
    list: "/assessments",
    detail: (id: string) => `/assessments/${id}`,
    reviewQueue: (id: string) => `/assessments/${id}/review-queue`,
    analytics: (id: string) => `/assessments/${id}/analytics`,
    reviewAttempt: (attemptId: string) => `/assessments/attempts/${attemptId}/review`,
    bulkDelete: "/assessments/bulk-delete",
    bulkStatus: "/assessments/bulk-status",
  },
  examResults: {
    list: "/exam-results",
    detail: (id: string) => `/exam-results/${id}`,
    bulkDelete: "/exam-results/bulk-delete",
  },
  fees: {
    plans: "/fees/plans",
    records: "/fees/records",
    recordDetail: (id: string) => `/fees/records/${id}`,
    bulkDeleteRecords: "/fees/records/bulk-delete",
    processEscalations: "/fees/automation/process-escalations",
  },
  attendance: {
    list: "/attendance",
    detail: (id: string) => `/attendance/${id}`,
    bulkCreate: "/attendance/bulk-create",
    bulkDelete: "/attendance/bulk-delete",
    bulkStatus: "/attendance/bulk-status",
    processFollowUps: "/attendance/automation/process-follow-ups",
  },
  reminders: {
    list: "/reminders",
    detail: (id: string) => `/reminders/${id}`,
    bulkDelete: "/reminders/bulk-delete",
    templates: "/reminders/templates",
    resetDefaultTemplates: "/reminders/templates/reset-defaults",
    templateDetail: (id: string) => `/reminders/templates/${id}`,
    rules: "/reminders/rules",
    ruleDetail: (id: string) => `/reminders/rules/${id}`,
    providerSettings: "/reminders/provider-settings",
    processDue: "/reminders/automation/process-due",
  },
  ai: {
    notices: "/ai/notices/generate",
    noticeCampaigns: "/ai/notices/campaigns",
    noticeCampaignAnalytics: "/ai/notices/analytics",
    noticeDeliveryAnalytics: "/ai/notices/delivery-analytics",
    reviewQueue: "/ai/review-queue",
    reviewQueueSummary: "/ai/review-queue/summary",
    organizationQueueSummary: "/ai/review-queue/organization-summary",
    organizationQueueTrend: "/ai/review-queue/organization-trend",
    scheduleNoticeCampaign: "/ai/notices/schedule",
    mailDraft: "/ai/mail-draft/generate",
    supportReply: "/ai/support/reply",
    admissionExtract: "/ai/admissions/extract",
    studentRiskRecommendation: "/ai/students/risk-recommendation",
    feeCollectionPlan: "/ai/fees/collection-plan",
    attendanceIntervention: "/ai/attendance/intervention",
    reminderDraft: "/ai/reminders/draft",
    usage: "/ai/usage",
  },
  mail: {
    list: "/mail",
    contacts: "/mail/contacts",
    conversation: (id: string) => `/mail/conversations/${id}`,
    reply: (id: string) => `/mail/conversations/${id}/reply`,
    detail: (id: string) => `/mail/${id}`,
    send: (id: string) => `/mail/${id}/send`,
    read: (id: string) => `/mail/${id}/read`,
    star: (id: string) => `/mail/${id}/star`,
    unstar: (id: string) => `/mail/${id}/unstar`,
    archive: (id: string) => `/mail/${id}/archive`,
    trash: (id: string) => `/mail/${id}/trash`,
    restore: (id: string) => `/mail/${id}/restore`,
  },
  portalMail: {
    list: "/portal/mail",
    contacts: "/portal/mail/contacts",
    conversation: (id: string) => `/portal/mail/conversations/${id}`,
    reply: (id: string) => `/portal/mail/conversations/${id}/reply`,
    detail: (id: string) => `/portal/mail/${id}`,
    send: (id: string) => `/portal/mail/${id}/send`,
    read: (id: string) => `/portal/mail/${id}/read`,
    star: (id: string) => `/portal/mail/${id}/star`,
    unstar: (id: string) => `/portal/mail/${id}/unstar`,
    archive: (id: string) => `/portal/mail/${id}/archive`,
    trash: (id: string) => `/portal/mail/${id}/trash`,
    restore: (id: string) => `/portal/mail/${id}/restore`,
  },
  activityLogs: {
    list: "/activity-logs",
  },
  reports: {
    summary: "/reports/summary",
    weeklyPrincipalSummary: "/reports/automation/weekly-principal-summary",
    totalStudents: "/reports/students/total",
    activeStudents: "/reports/students/active",
    enrollmentTrend: "/reports/students/enrollment-trend",
    studentStatusBreakdown: "/reports/students/status-breakdown",
    studentBatchDistribution: "/reports/students/batch-distribution",
    userRoleDistribution: "/reports/users/role-distribution",
    userStatusSummary: "/reports/users/status-summary",
    academicSummary: "/reports/academics/summary",
    unifiedReportCards: "/reports/academics/unified-report-cards",
    gradeDistribution: "/reports/academics/grade-distribution",
    examScheduleTrend: "/reports/academics/exam-schedule-trend",
    batchPerformance: "/reports/academics/batch-performance",
    resultStatusSummary: "/reports/academics/result-status",
    batchStatusSummary: "/reports/batches/status-summary",
    monthlyFeeCollection: "/reports/fees/monthly-collection",
    feeCollectionTrend: "/reports/fees/collection-trend",
    feeCollectionOverview: "/reports/fees/collection-overview",
    feePeriodComparison: "/reports/fees/period-comparison",
    batchCollection: "/reports/fees/batch-collection",
    feeStatusBreakdown: "/reports/fees/status-breakdown",
    unpaidFees: "/reports/fees/unpaid",
    attendanceSummary: "/reports/attendance/summary",
    attendanceStatusBreakdown: "/reports/attendance/status-breakdown",
    attendanceDailyTrend: "/reports/attendance/daily-trend",
    attendanceBatchSummary: "/reports/attendance/batch-summary",
    reminderChannelBreakdown: "/reports/reminders/channel-breakdown",
    reminderStatusBreakdown: "/reports/reminders/status-breakdown",
    reminderDailyTrend: "/reports/reminders/daily-trend",
  },
} as const;
