export const endpoints = {
  auth: {
    login: "/auth/login",
    refresh: "/auth/refresh",
    me: "/auth/me",
    logout: "/auth/logout",
    security: "/auth/security",
    revokeSession: (sessionId: string) => `/auth/sessions/${sessionId}/revoke`,
  },
  portalAuth: {
    login: "/portal-auth/login",
    refresh: "/portal-auth/refresh",
    me: "/portal-auth/me",
    logout: "/portal-auth/logout",
  },
  portal: {
    dashboard: "/portal/dashboard",
  },
  inquiries: {
    contact: "/inquiries/contact",
    list: "/inquiries",
    updateStatus: (id: string) => `/inquiries/${id}/status`,
  },
  users: {
    list: "/users",
    detail: (id: string) => `/users/${id}`,
  },
  organizations: {
    list: "/organizations",
    detail: (id: string) => `/organizations/${id}`,
    currentSettings: "/organization-settings/current",
  },
  organizationAssets: {
    list: "/organization-assets/current",
    detail: (id: string) => `/organization-assets/current/${id}`,
    download: (id: string) => `/organization-assets/current/${id}/download`,
  },
  roles: {
    list: "/roles",
    detail: (id: string) => `/roles/${id}`,
  },
  permissions: {
    list: "/permissions",
  },
  students: {
    list: "/students",
    import: "/students/import",
    importSample: "/students/import/sample",
    detail: (id: string) => `/students/${id}`,
    portalAccess: (id: string) => `/students/${id}/portal-access`,
    documents: (id: string) => `/students/${id}/documents`,
    documentDetail: (studentId: string, documentId: string) => `/students/${studentId}/documents/${documentId}`,
    documentDownload: (studentId: string, documentId: string) => `/students/${studentId}/documents/${documentId}/download`,
  },
  batches: {
    list: "/batches",
    detail: (id: string) => `/batches/${id}`,
  },
  academicSessions: {
    list: "/academic-sessions",
    detail: (id: string) => `/academic-sessions/${id}`,
  },
  subjects: {
    list: "/subjects",
    detail: (id: string) => `/subjects/${id}`,
  },
  teachers: {
    list: "/teachers",
    detail: (id: string) => `/teachers/${id}`,
  },
  batchSubjectAssignments: {
    list: "/batch-subject-assignments",
    detail: (id: string) => `/batch-subject-assignments/${id}`,
  },
  timetables: {
    list: "/timetables",
    detail: (id: string) => `/timetables/${id}`,
  },
  onlineClasses: {
    list: "/online-classes/sessions",
    detail: (id: string) => `/online-classes/sessions/${id}`,
    providerSettings: "/online-classes/provider-settings",
    runAutomation: "/online-classes/automation/run",
    automationSummary: "/online-classes/automation/summary",
    alerts: "/online-classes/alerts",
    generateMeet: (id: string) => `/online-classes/sessions/${id}/google-meet`,
    syncGoogleMeet: (id: string) => `/online-classes/sessions/${id}/google-meet/sync`,
    participants: (id: string) => `/online-classes/sessions/${id}/participants`,
    processAttendance: (id: string) => `/online-classes/sessions/${id}/process-attendance`,
  },
  exams: {
    list: "/exams",
    detail: (id: string) => `/exams/${id}`,
  },
  examResults: {
    list: "/exam-results",
    detail: (id: string) => `/exam-results/${id}`,
  },
  fees: {
    plans: "/fees/plans",
    records: "/fees/records",
    recordDetail: (id: string) => `/fees/records/${id}`,
  },
  attendance: {
    list: "/attendance",
    detail: (id: string) => `/attendance/${id}`,
  },
  reminders: {
    list: "/reminders",
    detail: (id: string) => `/reminders/${id}`,
    templates: "/reminders/templates",
    resetDefaultTemplates: "/reminders/templates/reset-defaults",
    templateDetail: (id: string) => `/reminders/templates/${id}`,
    rules: "/reminders/rules",
    ruleDetail: (id: string) => `/reminders/rules/${id}`,
    providerSettings: "/reminders/provider-settings",
    processDue: "/reminders/automation/process-due",
  },
  activityLogs: {
    list: "/activity-logs",
  },
  reports: {
    summary: "/reports/summary",
    totalStudents: "/reports/students/total",
    activeStudents: "/reports/students/active",
    enrollmentTrend: "/reports/students/enrollment-trend",
    studentStatusBreakdown: "/reports/students/status-breakdown",
    studentBatchDistribution: "/reports/students/batch-distribution",
    userRoleDistribution: "/reports/users/role-distribution",
    userStatusSummary: "/reports/users/status-summary",
    academicSummary: "/reports/academics/summary",
    gradeDistribution: "/reports/academics/grade-distribution",
    examScheduleTrend: "/reports/academics/exam-schedule-trend",
    batchPerformance: "/reports/academics/batch-performance",
    resultStatusSummary: "/reports/academics/result-status",
    batchStatusSummary: "/reports/batches/status-summary",
    monthlyFeeCollection: "/reports/fees/monthly-collection",
    feeCollectionTrend: "/reports/fees/collection-trend",
    feeCollectionOverview: "/reports/fees/collection-overview",
    feePeriodComparison: "/reports/fees/period-comparison",
    batchCollection: "/reports/fees/batch-collection",
    feeStatusBreakdown: "/reports/fees/status-breakdown",
    unpaidFees: "/reports/fees/unpaid",
    attendanceSummary: "/reports/attendance/summary",
    attendanceStatusBreakdown: "/reports/attendance/status-breakdown",
    attendanceDailyTrend: "/reports/attendance/daily-trend",
    attendanceBatchSummary: "/reports/attendance/batch-summary",
    reminderChannelBreakdown: "/reports/reminders/channel-breakdown",
    reminderStatusBreakdown: "/reports/reminders/status-breakdown",
    reminderDailyTrend: "/reports/reminders/daily-trend",
  },
} as const;
