export const PERMISSIONS = {
  users: ["users.create", "users.read", "users.update", "users.delete"],
  students: ["students.create", "students.read", "students.update", "students.delete"],
  portalAccess: ["portal-access.read", "portal-access.manage"],
  studentDocuments: ["student-documents.read", "student-documents.manage"],
  organizationAssets: ["organization-assets.read", "organization-assets.manage"],
  batches: ["batches.create", "batches.read", "batches.update", "batches.delete"],
  academicSessions: [
    "academic-sessions.create",
    "academic-sessions.read",
    "academic-sessions.update",
    "academic-sessions.delete",
  ],
  subjects: ["subjects.create", "subjects.read", "subjects.update", "subjects.delete"],
  teachers: ["teachers.create", "teachers.read", "teachers.update", "teachers.delete"],
  batchSubjectAssignments: [
    "batch-subject-assignments.create",
    "batch-subject-assignments.read",
    "batch-subject-assignments.update",
    "batch-subject-assignments.delete",
  ],
  timetables: ["timetables.create", "timetables.read", "timetables.update", "timetables.delete"],
  onlineClasses: [
    "online-classes.create",
    "online-classes.read",
    "online-classes.update",
    "online-classes.delete",
    "online-classes.sync",
    "online-classes.attendance",
  ],
  exams: ["exams.create", "exams.read", "exams.update", "exams.delete"],
  assignments: ["assignments.create", "assignments.read", "assignments.update", "assignments.delete"],
  assessments: ["assessments.create", "assessments.read", "assessments.update", "assessments.delete"],
  examResults: ["exam-results.create", "exam-results.read", "exam-results.update", "exam-results.delete"],
  fees: ["fees.create", "fees.read", "fees.update", "fees.delete"],
  attendance: ["attendance.create", "attendance.read", "attendance.update", "attendance.delete"],
  reminders: ["reminders.create", "reminders.read", "reminders.update", "reminders.delete"],
  reports: ["reports.read"],
  settings: ["settings.update"],
} as const;
